# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Inverness Electric
email: simonmacwebsite@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  High class electrical work for inverness and surrounding areas
  you will be shocked at the quaility and price... This is just a place holder Simon,
  you will have to come up with what you want in this description!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: WillGetYouToAddAFaceBokkPageForBuisnessToAddHere
github_username:  simonmacWeb
# Build settings
markdown: kramdown
